## Preprocesamiento de datos

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv("TC_Data_synthetic.csv")

In [4]:
df.head()

,cliente,entrega,devolución,masa_tortilla,masa_tamal,repartidor,fecha
0,lalo,14.0,0.0,0.0,0.0,diana,2025-01-15
1,leonor,5.5,0.0,0.0,0.0,diana,2025-07-05
2,paraiso,1.0,2.5,0.0,0.0,NaN,2021-01-01
3,tito,7.0,0.5,0.0,0.0,berta,2025-09-10
4,roberto,16.0,0.5,0.0,0.0,hilda,2022-10-07

In [5]:
df.dropna(subset=["fecha"], inplace=True)

In [6]:
df["repartidor"] = df["repartidor"].fillna("NA")

In [7]:
df["entrega"] = df["entrega"].fillna(0)

In [8]:
df.isna().sum()

cliente          0
entrega          0
devolución       0
masa_tortilla    0
masa_tamal       0
repartidor       0
fecha            0
dtype: int64

In [9]:
df['cliente_id'], unique_clientes = pd.factorize(df['cliente'])

In [10]:
df.drop(columns=["cliente"], inplace=True)

In [11]:
df["fecha"] = df["fecha"].astype("datetime64[ns]")

In [12]:
df["dia"] = df["fecha"].dt.isocalendar().day

In [13]:
df["mes"] = df["fecha"].dt.month

In [14]:
def estaciones(mes):
    if mes in [12, 1, 2]:
        return 1  # Invierno
    elif mes in [3, 4, 5]:
        return 2  # Primavera
    elif mes in [6, 7, 8]:
        return 3  # Verano
    else:
        return 4  # Otoño

df["estacion"] = df["mes"].apply(estaciones)

In [15]:
columna = df.pop('cliente_id')
df.insert(0, 'cliente_id', columna)

In [16]:
df['repartidor_id'], unique_repartidores = pd.factorize(df['repartidor'])
columna = df.pop('repartidor_id')
df.insert(5, 'repartidor_id', columna)

In [17]:
df.drop(["repartidor"], axis=1, inplace=True)

In [18]:
df["año"] = df["fecha"].dt.year
df["dia_mes"] = df["fecha"].dt.day

In [19]:
df.drop(["fecha"], axis=1, inplace=True)

In [20]:
df["dia_sem"] = df["dia"]
df.drop(["dia"], axis=1, inplace=True)

In [21]:
df["demanda_neta"] = df["entrega"] - df["devolución"]  # Variable determinante

df.drop(["masa_tortilla", "masa_tamal" ], axis=1, inplace=True)

In [22]:
df.head()

,cliente_id,entrega,devolución,repartidor_id,mes,estacion,año,dia_mes,dia_sem,demanda_neta
0,0,14.0,0.0,0,1,1,2025,15,3,14.0
1,1,5.5,0.0,0,7,3,2025,5,6,5.5
2,2,1.0,2.5,1,1,1,2021,1,5,-1.5
3,3,7.0,0.5,2,9,4,2025,10,3,6.5
4,4,16.0,0.5,3,10,4,2022,7,5,15.5

In [23]:
df.rename(columns={"devolución" : "devolucion"}, inplace=True)

In [24]:
df.head()

,cliente_id,entrega,devolucion,repartidor_id,mes,estacion,año,dia_mes,dia_sem,demanda_neta
0,0,14.0,0.0,0,1,1,2025,15,3,14.0
1,1,5.5,0.0,0,7,3,2025,5,6,5.5
2,2,1.0,2.5,1,1,1,2021,1,5,-1.5
3,3,7.0,0.5,2,9,4,2025,10,3,6.5
4,4,16.0,0.5,3,10,4,2022,7,5,15.5

In [25]:
df.to_csv("data_synthetic.csv")